using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderManagement.API.Models;
using OrderManagement.API.Data;

namespace OrderManagement.API.Controllers;

[ApiController]
[Route("api/[controller]")]

public class OrdersController(AppDbContext db) : ControllerBase
{
    private readonly AppDbContext _db = db;

    // GET /api/orders
    [HttpGet]

    public async Task<IActionResult> GetOrders()
    {
        try
        {
            var orders = await _db.Orders
                .AsNoTracking() // optimization: no change tracking needed for reads
                .OrderByDescending(order => order.CreatedAt)
                .ToListAsync();

            return Ok(orders);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { error = "Database error.", detail = ex.Message });
        }
    }

    [HttpPost]

    public async Task<IActionResult> CreateOrder([FromBody] Order order)
    {
        if (string.IsNullOrWhiteSpace(order.CustomerName) || 
            string.IsNullOrWhiteSpace(order.Product) || 
            order.Quantity <= 0 || 
            order.TotalPrice <= 0)
        {
            return BadRequest(new { error = "All fields are required and must be valid."});
        }

        try
        {
            order.Id = 0; // Ensure a new ID is generated by the database when creating the order
            order.CreatedAt = DateTime.UtcNow;
            _db.Orders.Add(order);
            await _db.SaveChangesAsync();
            return CreatedAtAction(nameof(GetOrders), new { id = order.Id }, order);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { error = "Could not save order.", detail = ex.Message });
        }
    } 
}